- name: "Backup redmine volumes"
  tags: redmine_backup
  shell: |
    docker run --rm -i -v {{ item.key }}:/volume:ro -v /tmp:/backup {{ alpine_image }} \
       tar -cjf /backup/{{item.value}}_backup_{{ inventory_hostname }}_{{ ansible_date_time.date }}.tar.bz2 -C /volume ./
  with_dict: "{{redmine_volumes}}"

- name: "Retrieve redmine backup files"
  tags: redmine_db_backup
  fetch:
    flat: True
    src: /tmp/{{ item.value }}_backup_{{ inventory_hostname }}_{{ ansible_date_time.date }}.tar.bz2
    dest: "{{ playbook_dir }}/{{ item.value }}_backup_{{ inventory_hostname }}_{{ ansible_date_time.date }}.tar.bz2"
  with_dict: "{{redmine_volumes}}"

- name: "Clean up backup files"
  file:
    name: "/tmp/{{ item.value }}_backup_{{ inventory_hostname }}_{{ ansible_date_time.date }}.tar.bz2"
    state: absent
  with_dict: "{{ redmine_volumes }}"
