- name: "Delete {{ item }} repository"
  command: >
    docker exec {{project_name}}_redmine_1 bash -c "rm -r {{repo_path}}{{item}}"
  when: item not in repositories

- name: "Remove repo update from crontab"
  command: >
    docker exec {{project_name}}_redmine_1 bash -c "crontab -u redmine -l | grep -v {{item}} |  crontab -u redmine -"
  when: item not in repositories
