- name: "Deploy redmine stack"
  docker_service:
    state: present
    project_src: /tmp/{{ project_name }}

- name: "Send ssh keys"
  copy:
    content: "{{ item.value }}"
    dest: /tmp/{{item.key}}
  with_dict: "{{redmine_ssh_keys}}"

- name: "Add ssh keys and cron"
  shell: |
    docker exec {{project_name}}_redmine_1 bash -c "apt-get update;\
        apt-get install -y cron"

    docker exec {{project_name}}_redmine_1 bash -c "mkdir -p /home/redmine/.ssh"
        
    docker cp /tmp/id_rsa {{project_name}}_redmine_1:/home/redmine/.ssh/id_rsa;
    docker cp /tmp/id_rsa.pub {{project_name}}_redmine_1:/home/redmine/.ssh/id_rsa.pub;

    docker exec {{project_name}}_redmine_1 bash -c chown redmine -R "/home/redmine"

- name: "Delete ssh keys"
  file:
    name: /tmp/{{item.key}}
    state: absent
  with_dict: "{{redmine_ssh_keys}}"

