- name: "Add redmine container to inventory"
  tags: redmine_repos
  add_host:
    name: "{{projet_name}}_redmine_1"
    ansible_connection: docker
  changed_when: false

- name: "Repository operations"
  block:
  tags: redmine_repos
  delegate_to: "{{project_name}}_redmine_1" 

    - name: "List repositories"
      become: True
      command: ls {{repo_path}}
      register: repo_list
    
    - name: "List repos in crontab"
      become: True
      command: crontab -u redmine -l"
      register: cron_repos
    
    - name: "Create ssh folder if it does not exist"
      command: "mkdir -p /home/redmine/.ssh; chown redmine -R /home/redmine"
    
    - name: "Touch ssh config file"
      command: "touch /home/redmine/.ssh/config"
    
    
    - include_tasks: add_repos.yml
      become: True
      with_dict: "{{repositories}}"
    
    - name: "Delete removed repositories"
      become: True
      include_tasks: del_repos.yml
      with_items: "{{ repo_list.stdout.split() }}"
