- name: "Copy data from backup folder to remote host"
  tags:
    - redmine_restore
  copy:
    src: "{{ item }}"
    dest: /tmp/{{ item.key }}
  with_dict: "{{ redmine_backups }}"

- name: "Stopping redmine stack"
  docker_service:
    state: absent
    project_src: /tmp/{{ project_name }}

- name: "restore data from backup"
  tags: redmine_restore
  shell: |
    docker run --rm -i -v {{ item.value }}:/redmine -v /tmp:/backup:ro \
        {{ alpine_image }} \
        sh -c "\
        apk update;\
        apk add -y tar;\
        rm -rf /redmine/* ;\
        tar -C /redmine/ -xjf /backup/{{ item.key }};"
  with_dict: "{{redmine_backups}}"

- name: "Remove backup data"
  tags:
    - redmine_restore
  file:
    name: /tmp/{{ item.key }}
    state: absent
  with_dict: "{{redmine_backups}}"
