- name: "Update local redmine clean image"
  docker_image:
    name: redmine:latest
    state: present
    force: True
    pull: True

- name: "Start temporary clean redmine service to copy files"
  docker_container:
    name: tmp_redmine
    env:
      REDMINE_NO_DB_MIGRATE: True
    image: redmine:latest
    state: started
    volumes:
      - "{{ redmine_volumes.REDMINE_VOLUME }}:/redmine_files"
      - "{{ redmine_volumes.REDMINE_GEMS_VOLUME}}:/redmine_gems"

- name: "Copy configuration to server"
  template:
    src: configuration.j2
    dest: /tmp/configuration.yml

- name: "Install plugins"
  command: docker exec tmp_redmine bash -c "cd /usr/src/redmine/plugins; {{item.value}}"
  with_dict: "{{redmine_plugins }}"

- name: "Start temporary clean maria service to copy files"
  docker_container:
    name: tmp_db
    image: mariadb
    state: started
    env:
      MYSQL_ROOT_PASSWORD: "{{ REDMINE_DB_PASSWORD }}"
    volumes:
      - "{{ redmine_volumes.REDMINE_DB_VOLUME }}:/maria_files"

- name: "Wait 5 seconds for db to start up"
  pause:
    seconds: 5

- name: "Copy clean files to docker volumes"
  shell: |
    docker exec tmp_redmine bash -c "cp -a /usr/src/redmine/. /redmine_files;"
    docker exec tmp_redmine bash -c "cp -a /usr/local/bundle/. /redmine_gems;"

    docker exec -u redmine tmp_redmine bash -c "mkdir -p /redmine_files/repos /redmine_files/uploads"

    docker cp /tmp/configuration.yml tmp_redmine:/redmine_files/config/configuration.yml

    docker exec tmp_db cp -a /var/lib/mysql/. /mariafiles
  retries: 3

- name: "Stop temporary services"
  docker_container:
    name: "{{ item }}"
    state: absent
  with_items:
    - tmp_db
    - tmp_redmine

- name: "Delete conf file"
  file:
    name: /tmp/configuration.yml
    state: absent
