- name: "check if {{ item.value }} exists"
  command: docker volume inspect {{ item.value }}
  register: myvolume_exists
  ignore_errors: True

- name: "create {{ item.value }}"
  command: "docker volume create --name {{ item.value }}"
  when: myvolume_exists|failed
